server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8010/eureka  # discovery service location

spring:
  application:
    name: Gateway_Service
#  cloud:
#    gateway:
#      routes:
#      - id: userModule
#        uri: lb://User_Service
#        predicates:
#        - Path=/users/**
#      - id: bookModule
#        uri: lb://Book_Service
#        predicates:
#        - Path=/books/**