service: DictionaryGetGoogleTranslation-python

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  timeout: 30
  iam:
    role: arn:aws:iam::052752173794:role/LambdaExecutionWithCloudWatch

functions:
  sender:
    memorySize: 512
    handler: googleTranslationHandler.translate
    events:
      - sqs:arn:aws:sqs:ap-southeast-2:052752173794:NewWordQueue
      - sqs:
          arn:
            Fn::GetAtt:
              - TestWordQueue
              - Arn
          batchSize: 1
          maximumBatchingWindow: 60

    layers:
      - arn:aws:lambda:ap-southeast-2:052752173794:layer:chrome_driver_57:1
      - arn:aws:lambda:ap-southeast-2:052752173794:layer:selenium:1

resources:
  Resources:
    TestWordQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TestWordQueue"