service: DictionaryGetGoogleTranslation-python

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  timeout: 40
  iam:
    role: arn:aws:iam::052752173794:role/LambdaExecutionWithCloudWatch

functions:
  dispatcher:
    memorySize: 512
    handler: handler.main
    events:
      - sns:arn:aws:sns:ap-southeast-2:052752173794:NewWordTopic

    layers:
      - arn:aws:lambda:ap-southeast-2:052752173794:layer:chrome_driver_57:1
      - arn:aws:lambda:ap-southeast-2:052752173794:layer:selenium:1

resources:
  Resources:
    TestWordQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TestWordQueue"